### ISSUE TITLE
It is not supporting  to visual studio 2019. I have cloud license version  for this so it is supporting to visual studio 2022. But for visual studio 2019 it is not working 

### ISSUE THREAD

**Issue by jishang1602** [Checkmarx/ast-visual-studio-extension#34]

**Comment by Yoavast** [comment]
Dear @jishang1602  visual studio 2019 is not supprted by design.
We are currently focusing on supporting the latest editions of Visual Studio, including other IDE vendors like Jetbrain Eclipse and others.

Regards,
Yoav Ast | Checkmarx Product Manager
